var JS_EX_LOGIN = "LOGIN";
var JS_EX_ANOTHERLOGIN = "ANOTHERLOGIN";
var JS_EX_ERROR_DB = "ERROR_DB";
var JS_EX_TAXCODE_EXISTS_REGISTER = "TAXCODE_EXISTS_REGISTER";
var JS_EX_GREAT_SIZE = "GREAT_SIZE";
var JS_EX_ERROR = "ERROR";
var JS_EX_CSRF = "CSRF";
var JS_EX_STATUS = "HAS_STATUS";
var JS_EX_DENIED_FUNCTION = "DENIED_FUNCTION";
var JS_EX_NO_APPROVE_AGENCY = "NO_APPROVE_AGENCY";
var JS_EX_ERROR_CORECA_CALL = "ERROR_CORECA_CALL";
var JS_EX_CSR_KEYSIZE = "CSR_KEYSIZE";
var JS_EX_RSSP_USERNAME_EXISTS = "RSSP_USERNAME_EXISTS";
var JS_EX_CSR_EXISTS = "CSR_EXISTS";
var JS_EX_CSR_NULL = "CSR_NULL";
var JS_EX_DNS_SSL_NULL = "DNS_SSL_NULL";
var JS_EX_STATUS_TOKEN = "HAS_STATUS_TOKEN";
var JS_EX_SPECIAL = "SPECIAL";
var JS_EX_FILE_SIZE = "FILE_SIZE";
var JS_EX_FILE_EXTENTION = "FILE_EXTENTION";
var JS_EX_NO_DATA_WRITE = "NO_DATA_WRITE";
var JS_EX_CERT1 = "ERRORCERT";
var JS_EX_CERT1_EXPIRE = "ERROREXPIRECERT";
var JS_EX_CERT2 = "ERRORCERT2";
var JS_EX_CERT2_EXPIRE = "ERROREXPIRECERT2";
var JS_EX_NO_UTF8 = "NOUTF-8";
var JS_EX_NO_DATA = "NO_DATA";
var JS_EX_NO_LOCK = "NO_LOCK";
var JS_EX_HAS_CANC = "HAS_CANC";
var JS_EX_HAS_BLOC = "HAS_BLOC";
var JS_EX_ERRORCTS = "ERRORCTS";
var JS_EX_ERRORCSR = "ERRORCSR";
var JS_EX_NO_CERTCHAN = "NO_CERTCHAN";
var JS_EX_NOEXISTS_TOKEN = "NOEXISTS_TOKEN";
var JS_EX_LESS = "LESS";
var JS_EX_NULL = "NULL";
var JS_EX_ERROR_KEY = "error_key";
var JS_EX_ERROR_CSR = "error_csr";
var JS_EX_ERROR_WORKER = "error_worker";
var JS_EX_ERROR_NOWORKER = "error_noworker";
var JS_EX_INVALID_EXTERNAL_SYSTEM = "INVALID_EXTERNAL_SYSTEM";
var JS_EX_EXCEL_FORMAT_INVALIE = "FORMAT_INVALIE";
var JS_EX_EXCEL_NOT_SIZE = "NOT_SIZE";
var JS_EX_EXCEL_NOT_CA = "NOT_CA";
var JS_EX_CSV_NO_CHANNEL = "CSV_NO_CHANNEL";
var JS_EX_CSV_NO_USER = "CSV_NO_USER";
var JS_EX_CSV_NO_CA = "CSV_NO_CA";
var JS_EX_CSV_NO_WORKERID = "CSV_NO_WORKERID";
var JS_EX_CSV_NO_CSR = "CSV_NO_CSR";
var JS_EX_CSV_NO_CERTIFICATE = "CSV_NO_CERTIFICATE";
var JS_EX_CSV_NO_CERTIFICATECHAIN = "CSV_NO_CERTIFICATECHAIN";
var JS_EX_CSV_NO_LICENSE_TYPE = "CSV_NO_LICENSE_TYPE";
var JS_STR_GRID_SEARCH_RESET = "new";
var JS_STR_GRID_COMBOBOX_VALUE_ALL = "All";
var JS_STR_ACTION_TIMEOUT = "1000";
var JS_STR_TIMEOUT_REVOKE_WPKI = "5000";
var JS_EX_NO_FORMFACTOR = "NO_FORMFACTOR";
var JS_EX_METHOD_OTP_EMPTY = "OTP_EMPTY";
var JS_EX_METHOD_BILLCODE_EMPTY = "BILLCODE_EMPTY";
var JS_STR_CLIENT_METHOD_OTPSMS = "OTPSMS";
var JS_STR_CLIENT_METHOD_OTPEMAIL = "OTPEmail";
var JS_STR_CLIENT_METHOD_OTPHARDWARE = "OTPHardware";
var JS_STR_CLIENT_METHOD_WPKI = "WPKI";
var JS_STR_CLIENT_RESPONSECODE_WAITSECOND_WPKI = "116";
var JS_STR_CHOISE_ANOTHER_NUMBER = "{NUMBER}";
var JS_STR_COMPONENT_DN_VALUE_MNS = "MNS";
var JS_STR_COMPONENT_DN_VALUE_MST = "MST";
var JS_STR_COMPONENT_DN_VALUE_CMND = "CMND";
var JS_STR_COMPONENT_DN_VALUE_HC = "HC";

var JS_STR_COMPONENT_DN_VALUE_TIN = "TIN";
var JS_STR_COMPONENT_DN_VALUE_BGC = "BGC";
var JS_STR_COMPONENT_DN_VALUE_DEC = "DEC";
//if(JS_LANGUAGE_TEMPLATE_UID_PREFIX === "2"){
//    JS_STR_COMPONENT_DN_VALUE_DEC = "DEC";
//}
var JS_STR_COMPONENT_DN_VALUE_PID = "PID";
var JS_STR_COMPONENT_DN_VALUE_PPID = "PPID";
var JS_STR_COMPONENT_DN_VALUE_PEID = "PEID";
var JS_STR_COMPONENT_DN_VALUE_SIC = "SIC";
var JS_STR_COMPONENT_DN_VALUE_UNC = "UNC";

var JS_STR_COMPONENT_DN_VALUE_PREFIX_MNS = "MNS:";
if(JS_LANGUAGE_TEMPLATE_UID_PREFIX === "0"){
    JS_STR_COMPONENT_DN_VALUE_PREFIX_MNS = "BGC:";
}
var JS_STR_COMPONENT_DN_VALUE_PREFIX_MST = "MST:";
if(JS_LANGUAGE_TEMPLATE_UID_PREFIX === "0"){
    JS_STR_COMPONENT_DN_VALUE_PREFIX_MST = "TIN:";
}
var JS_STR_COMPONENT_DN_VALUE_PREFIX_QD = "QĐ:";
if(JS_LANGUAGE_TEMPLATE_UID_PREFIX === "0"){
    JS_STR_COMPONENT_DN_VALUE_PREFIX_QD = "DEC:";
}
//else if(JS_LANGUAGE_TEMPLATE_UID_PREFIX === "2"){
//    JS_STR_COMPONENT_DN_VALUE_PREFIX_QD = "MDV:";
//}
var JS_STR_COMPONENT_DN_VALUE_PREFIX_BHXH = "BHXH:";
if(JS_LANGUAGE_TEMPLATE_UID_PREFIX === "0") {
    JS_STR_COMPONENT_DN_VALUE_PREFIX_BHXH = "SIC:";
}
var JS_STR_COMPONENT_DN_VALUE_PREFIX_MDV = "MDV:";
if(JS_LANGUAGE_TEMPLATE_UID_PREFIX === "0") {
    JS_STR_COMPONENT_DN_VALUE_PREFIX_MDV = "UNC:";
}
var JS_STR_COMPONENT_DN_RADIO_ID_MST_MNS = "MST_MNS";
var JS_STR_COMPONENT_DN_RADIO_ID_CMND_HC = "CMND_HC";
var JS_STR_COMPONENT_DN_RADIO_ID_EXTEND = "_TEXT";
var JS_STR_COMPONENT_DN_CHANGEINFO_BEFORE_EXTEND = "_BEFORE";
var JS_STR_COMPONENT_DN_VALUE_PREFIX_CMND = "CMND:";
if(JS_LANGUAGE_TEMPLATE_UID_PREFIX === "0"){
    JS_STR_COMPONENT_DN_VALUE_PREFIX_CMND = "PID:";
}
var JS_STR_COMPONENT_DN_VALUE_PREFIX_CCCD = "CCCD:";
if(JS_LANGUAGE_TEMPLATE_UID_PREFIX === "0"){
    JS_STR_COMPONENT_DN_VALUE_PREFIX_CCCD = "PEID:";
}
var JS_STR_COMPONENT_DN_VALUE_PREFIX_HC = "HC:";
if(JS_LANGUAGE_TEMPLATE_UID_PREFIX === "0"){
    JS_STR_COMPONENT_DN_VALUE_PREFIX_HC = "PPID:";
}
var JS_STR_COMPONENT_DN_VALUE_PHONE = "telephoneNumber";
var JS_STR_COMPONENT_DN_VALUE_EMAIL = "E";
var JS_STR_COMPONENT_DN_VALUE_CITYPROVINCE = "ST";
var JS_STR_COMPONENT_DN_VALUE_LOCALITY = "L";
var JS_STR_COMPONENT_DN_VALUE_COUNTRY = "C";
var JS_STR_COMPONENT_DN_VALUE_TITLE = "T";
var JS_STR_COMPONENT_DN_VALUE_COMMONNAME = "CN";
var JS_STR_COMPONENT_DN_VALUE_DOMAINNAME = "Domain";
var JS_STR_COMPONENT_DN_VALUE_COMMONNAME_TYPE_PERSON = "PERSON";
var JS_STR_COMPONENT_DN_VALUE_COMMONNAME_TYPE_COMPANY = "COMPANY";
var JS_STR_COMPONENT_DN_VALUE_COMMONNAME_TYPE_DOMAIN_NAME = "DOMAIN_NAME";
var JS_STR_COMPONENT_DN_VALUE_ORGANUNIT = "OU";
var JS_STR_COMPONENT_DN_VALUE_ORGANI = "O";
var JS_STR_COMPONENT_DN_VALUE_UID = "0.9.2342.19200300.100.1.1";
var JS_STR_COMPONENT_DN_VALUE_UID_BEFORE = "UID";
var JS_STR_COMPONENT_DN_VALUE_UID_TEXT_FIELD = "TEXT_FIELD";
var JS_STR_COMPONENT_DN_VALUE_UID_TEXT_FIELD_SAN = "TEXT_FIELD_SAN";
var JS_STR_COMPONENT_DN_VALUE_UID_RADIO_BUTTON = "RADIO_BUTTON";
var JS_STR_COMPONENT_DN_VALUE_LIST_RADIO_BUTTON = "RADIO_LIST";
var JS_STR_COMPONENT_DN_VALUE_UID_COMBOBOX_LIST_COMPANY = "UID_LIST/COMPANY";
var JS_STR_COMPONENT_DN_VALUE_UID_COMBOBOX_LIST_PERSONAL = "UID_LIST/PERSONAL";
var JS_STR_COMPONENT_DN_VALUE_UID_COMBOBOX_LIST_COMPANY_INPUT_ID = "UID_INPUT_COMPANY";
var JS_STR_COMPONENT_DN_VALUE_UID_COMBOBOX_LIST_PERSONAL_INPUT_ID = "UID_INPUT_PERSONAL";
var JS_STR_COMPONENT_DN_VALUE_UID_COMBOBOX_LIST_COMPANY_CBX_ID = "UID_CBX_COMPANY";
var JS_STR_COMPONENT_DN_VALUE_UID_COMBOBOX_LIST_PERSONAL_CBX_ID = "UID_CBX_PERSONAL";
var JS_STR_COMPONENT_DN_VALUE_E_SAN = "rfc822Name";
var JS_STR_TAG_PIN = "PIN";
var JS_STR_TAG_ENABLE = "ENABLE";
var JS_STR_TAG_WORKERGENID1_PIN = "WORKERGENID1.PIN";
var JS_STR_ACTIVE_TRUE = "True";
var JS_STR_ACTIVE_FALSE = "False";
var JS_STR_GRID_STRING_NA = "N/A";
var JS_STR_ERROR_CODE_99 = "99";
var JS_STR_TAG_ID_RECORD = "id_";
var JS_STR_POLICY_TAG_BO_FORGOT_PASSWORD_USER = "BO_FORGOT_PASSWORD_USER";
var JS_STR_POLICY_TAG_BO_REQUEST_CHANGE_PASSWORD = "BO_REQUEST_CHANGE_PASSWORD";
var JS_STR_POLICY_TAG_FO_SEND_MAIL_HA_MONITORING = "FO_SEND_MAIL_HA_MONITORING";
var JS_STR_POLICY_TAG_BO_TOKEN_AMOUNT = "BO_TOKEN_AMOUNT";
var JS_STR_POLICY_TAG_FO_DEFAULT_PUSH_NOTICE_JSON = "FO_DEFAULT_PUSH_NOTICE_JSON";

var JS_STR_TOKEN_TAG_PUSH_NOTICE_TEXT_COLOR = "PUSH_NOTICE_TEXT_COLOR";
var JS_STR_TOKEN_TAG_PUSH_NOTICE_BGR_COLOR = "PUSH_NOTICE_BGR_COLOR";
var JS_STR_TOKEN_TAG_PUSH_NOTICE_CONTENT = "PUSH_NOTICE_CONTENT";
var JS_STR_TOKEN_TAG_PUSH_NOTICE_URL = "PUSH_NOTICE_URL";

var JS_STR_POLICY_TAG_FO_LANGUAGE = "FO_LANGUAGE";
var JS_STR_USER_STATE_CANCEL_ID = "4";
var JS_STR_POLICY_MIMETYPE_NUMERIC = "text/numeric";
var JS_STR_POLICY_MIMETYPE_BOOLEAN = "text/boolean";
var JS_STR_POLICY_MIMETYPE_TEMPLATE = "text/template";
var JS_STR_POLICY_MIMETYPE_COMBOBOX_CA = "text/combobox/ca";
var JS_STR_POLICY_MIMETYPE_COMBOBOX_BRANCH = "text/combobox/branch";
var JS_STR_POLICY_MIMETYPE_DATETIME = "text/datetime";
var JS_STR_POLICY_MIMETYPE_COLOR = "text/color";
var JS_STR_POLICY_MIMETYPE_JSON_PUSHNOTIFICATION = "text/json/pushnotification";
var JS_STR_POLICY_MIMETYPE_JSON_NOTIFICATION_RECORD_COLLECTION = "text/json/collectionnotice";
var JS_STR_POLICY_MIMETYPE_TEXT = "text/alphanumeric";
var JS_STR_POLICY_REFIX_ID_RADIO_EN = "_EN";
var JS_STR_POLICY_REFIX_ID_RADIO_VN = "_VN";
var JS_STR_VALUE_LESS_ZERO = "-1";
var JS_STR_CHOISE_ANOTHER_DATE_YEAR = "{DATE_YEAR}";
var JS_STR_FORGOT_CONFIRM_EMAIL = "{EMAIL}";

var JS_EX_CSV_NO_TOKENID = "CSV_NO_TOKENID";
var JS_EX_CSV_NO_SOPIN = "CSV_NO_SOPIN";
var JS_EX_CSV_NO_AGENCY = "CSV_NO_AGENCY";
var JS_EX_CSV_NO_COLUMN = "CSV_NO_COLUMN";
var JS_EX_WRONG_AGENCY = "WRONG_AGENCY";
var JS_EX_WRONG_ROLE = "WRONG_ROLE";
var JS_EX_NOEMAIL = "NO_EMAIL";
var JS_STR_CERTIFICATION_PURPOSE_CODE_TOKEN = "TOKEN";
var JS_STR_CERTIFICATION_PURPOSE_CODE_SSL = "SSL";
var JS_STR_CERTIFICATION_PURPOSE_CODE_CODE_SIGNING = "CODE_SIGNING";
var JS_STR_CERTIFICATION_PURPOSE_ID_SSL = "2";
var JS_STR_CERTIFICATION_PURPOSE_ID_CODE_SIGNING = "3";
var JS_STR_CERTIFICATION_PURPOSE_ID_STAFF = "4";
var JS_STR_CERTIFICATION_PURPOSE_ID_ENTERPRISE = "5";
var JS_STR_CERTIFICATION_PURPOSE_ID_PERSONAL = "6";
var JS_STR_CERTIFICATION_PURPOSE_ID_PERSONAL_GOV = "8";
var JS_STR_CERTIFICATION_PURPOSE_ID_ENTERPRISE_GOV = "9";
var JS_STR_CERTIFICATION_PURPOSE_ID_SIGNSERVER_STAFF = "8";
var JS_STR_CERTIFICATION_PURPOSE_ID_SIGNSERVER_ENTERPRISE = "7";
var JS_STR_CERTIFICATION_PURPOSE_ID_SIGNSERVER_PERSONAL = "9";
var JS_STR_CERTIFICATION_PURPOSE_ID_DEVICE = "7";
var JS_STR_CERTIFICATION_ATTR_TYPE_ID_REGISTRATION = "1";
var JS_STR_CERTIFICATION_ATTR_TYPE_ID_RENEWAL = "2";
var JS_STR_CERTIFICATION_ATTR_TYPE_ID_CHANGEINFO = "3";
var JS_STR_CERTIFICATION_ATTR_TYPE_ID_REVOKE = "4";
var JS_STR_CERTIFICATION_ATTR_TYPE_ID_COMPENSATION = "5";
var JS_STR_CERTIFICATION_ATTR_TYPE_ID_REISSUE = "6";
var JS_STR_CERTIFICATION_ATTR_TYPE_ID_PERMANENT_DISABLE = "9";
var JS_STR_CERTIFICATION_ATTR_TYPE_ID_TEMPORARY_DISABLE = "10";
var JS_STR_CERTIFICATION_ATTR_TYPE_ID_RECOVERED = "8";
var JS_STR_CERTIFICATION_ATTR_TYPE_ID_BUY_MORE = "13";
var JS_STR_AGENT_ROOT = "1";
var JS_STR_SERVICE_TYPE_ID_REGISTRATION = "2";
var JS_STR_SERVICE_TYPE_ID_RENEWAL = "3";
var JS_STR_SERVICE_TYPE_ID_CHANGEINFO = "4";
var JS_STR_SERVICE_TYPE_ID_SUSPEND = "5";

var JS_STR_ROLE_ATTRIBUTE_TYPE_TOKEN = "TOKEN_ROLE";
var JS_STR_ROLE_ATTRIBUTE_TYPE_CERT = "CERTIFICATE_ROLE";
var JS_STR_ROLE_ATTRIBUTE_TYPE_ANOTHER = "ANOTHER";
var JS_STR_ROLE_ADMIN_SUPER_CA = "1";
var JS_STR_ROLE_ADMIN_CA = "9";

var JS_STR_EXPORT_TYPE_REPORT_CERT_TOKEN = "REPORT_CERT_TOKEN";
var JS_STR_EXPORT_TYPE_REPORT_CERT_SIGNSERVER = "REPORT_CERT_SIGNSERVER";
// PKI FORMFACTOR
var JS_STR_PKI_FORMFACTOR_ID_HARD_TOKEN = "2";
var JS_STR_PKI_FORMFACTOR_ID_SOFT_TOKEN = "3";
var JS_STR_PKI_FORMFACTOR_ID_ESIGNCLOUD = "4";
var JS_STR_PKI_FORMFACTOR_ID_REMOTE_SIGNING = "5";
var JS_STR_PKI_FORMFACTOR_ID_PKI_USIM = "10";
var JS_STR_PKI_FORMFACTOR_ID_HARD_TOKEN_SAFENET = "7";
var JS_STR_PKI_FORMFACTOR_ID_HARD_TOKEN_SMARTCARD = "8";
var JS_STR_PKI_FORMFACTOR_ID_HARD_TOKEN_EPASS3003 = "9";
// OWNER TYPE
var JS_STR_OWNER_TYPE_ID_ENTERPRISE = "2";
var JS_STR_OWNER_TYPE_ID_STAFF = "3";
var JS_STR_OWNER_TYPE_ID_PERSONAL = "4";
var JS_STR_OWNER_TYPE_ID_ENTERPRISE_GOV = "5";
var JS_STR_OWNER_TYPE_ID_PERSONAL_GOV = "6";
// AGENCY CA
var JS_STR_AGENCY_ROOT_CA = "1";
// FILE PROFILE
var JS_STR_FILE_PROFILE_CODE_E_CONTRACT="DIGITAL-CERTIFICATE";
var JS_STR_FILE_PROFILE_CODE_AGREEMENT_PAPER="AGREEMENT_PAPER";
var JS_STR_JSON_PROFILE_LIST_ITEM="PROFILE_LIST/ITEM";
var JS_STR_JSON_SERVICE_TYPE_ITEM="SERVICE_TYPE/ITEM";
var JS_STR_JSON_MAJOR_TYPE_ITEM="MAJOR_TYPE/ITEM";
// REASON CORECA
var JS_STR_REASON_CORECA_UNSPECIFIED = "10";
// mode external system
var JS_STR_PKI_FORMFACTOR_MODE_DIRECT = "DIRECT";
var JS_EX_CSV_NO_TOKENSN = "CSV_NO_TOKENSN";
var JS_EX_CSV_NO_MST = "CSV_NO_MST";
var JS_EX_CSV_NO_STT = "CSV_NO_STT";
// change ICA
var JS_IS_WHICH_ABOUT_CA_ICA = "18";
var JS_IS_WHICH_ABOUT_CA_NC = "7";
var JS_IS_WHICH_ABOUT_CA_HILO = "20";
var JS_IS_WHICH_ABOUT_CA_WINCA = "14";
var JS_IS_WHICH_ABOUT_CA_CMC = "8";
var JS_IS_WHICH_ABOUT_CA_MID = "3";
var JS_IS_WHICH_ABOUT_CA_MATBAO = "22";
var JS_IS_WHICH_ABOUT_CA_FPT = "10";