
package vn.mobileid.esigncloud.management;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Management", targetNamespace = "http://management.esigncloud.mobileid.vn/", wsdlLocation = "https://192.168.2.249:10443/eSignCloud/Management?wsdl")
public class Management_Service
    extends Service
{

    private final static URL MANAGEMENT_WSDL_LOCATION;
    private final static WebServiceException MANAGEMENT_EXCEPTION;
    private final static QName MANAGEMENT_QNAME = new QName("http://management.esigncloud.mobileid.vn/", "Management");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://192.168.2.249:10443/eSignCloud/Management?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANAGEMENT_WSDL_LOCATION = url;
        MANAGEMENT_EXCEPTION = e;
    }

    public Management_Service() {
        super(__getWsdlLocation(), MANAGEMENT_QNAME);
    }

    public Management_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGEMENT_QNAME, features);
    }

    public Management_Service(URL wsdlLocation) {
        super(wsdlLocation, MANAGEMENT_QNAME);
    }

    public Management_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGEMENT_QNAME, features);
    }

    public Management_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Management_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Management
     */
    @WebEndpoint(name = "ManagementPort")
    public Management getManagementPort() {
        return super.getPort(new QName("http://management.esigncloud.mobileid.vn/", "ManagementPort"), Management.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Management
     */
    @WebEndpoint(name = "ManagementPort")
    public Management getManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://management.esigncloud.mobileid.vn/", "ManagementPort"), Management.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGEMENT_EXCEPTION!= null) {
            throw MANAGEMENT_EXCEPTION;
        }
        return MANAGEMENT_WSDL_LOCATION;
    }

}
